# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ed3b44d608ef5133325cfe0dcc9f4912b7e78fd01fbb625236582004b22aca2656efd16e0d3ca03f594dcff6ae1a34e543c2f29261d7243f8b4e6973f6b9a44e

test:
  secret_key_base: d70fd6a028ef3aa8351a36c49e25c7b88f8095075926a8e255d604f8aec1e06acf0a1fbcd08b843a0d4524f8ee371f9b0b052e854bb2599657de008e93687910

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
